name: Pull Request Action
on:
  pull_request_target:
    types: [ closed ]
    branches: [main, test]
  #push:
  #  branches:
  #    - main
      
jobs:
  create-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: |
        echo PR #${{ github.event.number }} has been merged (commit ${{ github.sha }})
        if [ "${{ github.base_ref }}" == 'main' ]; then
          echo 'target_branch=test' >> $GITHUB_ENV
          echo 'pr_branch_prefix=tcand' >> $GITHUB_ENV
        elif [ '${{ github.base_ref }}' == 'test' ]; then
          echo 'target_branch=prod' >> $GITHUB_ENV
          echo 'pr_branch_prefix=pcand' >> $GITHUB_ENV
        fi
    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: '[Example] Simple demo',
            owner,
            repo,
            head: '${{ github.head_ref }}',
            base: '${{ env.target_branch }}',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['feature', 'automated pr']
          });
