name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request_target:
    types: [ closed ]
    branches: [main, test]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: |
        echo PR #${{ github.event.number }} has been merged (commit ${{ github.sha }})
        if [ "${{ github.base_ref }}" == 'main' ]; then
          echo 'target_branch=test' >> $GITHUB_ENV
          echo 'pr_branch_prefix=tcand' >> $GITHUB_ENV
        elif [ '${{ github.base_ref }}' == 'test' ]; then
          echo 'target_branch=prod' >> $GITHUB_ENV
          echo 'pr_branch_prefix=pcand' >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v3
      with:
        ref: "${{ github.base_ref }}"
        fetch-depth: 0
    - run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git cherry-pick ${{ github.sha }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: Cherry picked contents from (#${{ github.event.number }})
          title: (To ${{ env.target_branch }}) ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          branch: ${{ env.pr_branch_prefix }}/${{ github.head_ref }}

  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
          
# $GITHUB_HEAD_REF is source branch
# $GITHUB_BASE_REF is target branch
