name: Delete old Releases

on:
  workflow_call:

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Remove old releases
        run: |
          gh release list --limit 500 --json 'isPrerelease,name,tagName' \
          | while read releases; do
            for row in $(echo "${releases}" | jq -r '.[] | @base64'); do
              _jq() {
               echo ${row} | base64 --decode | jq -r ${1}
              }
              if [[ "$(_jq '.name')" =~ ^"${{ inputs.release-name-prefix }}" ]]; then
                echo "$(_jq '.tagName')" - "${{ needs.createversionandtag.outputs.tag-name }}"
                if [[ ! "$(_jq '.tagName')" == "${{ needs.createversionandtag.outputs.tag-name }}" ]]; then
                  echo Deleting Release $(_jq '.name');
                  
                  --gh release delete -y "$(_jq '.tagName')";
                  
                fi
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.ELSE_CORE_NUGET }}
