name: Delete old Releases

on:
  workflow_dispatch:
    inputs:
      old-versions-to-keep:
        default: '1'
        type: number

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Remove old releases
        run: |
          declare -i releaseIndex=0;
          gh release list --limit 30 --json 'isPrerelease,name,tagName' --order desc \
          | while read releases; do
            for row in $(echo "${releases}" | jq -r '.[] | @base64'); do
              releaseIndex+=1

              echo "$releaseIndex"
              echo "${{ inputs.old-versions-to-keep }}"
              
              if [ "$releaseIndex" -gt "${{ inputs.old-versions-to-keep }}" ]; then
                _jq() {
                 echo ${row} | base64 --decode | jq -r ${1}
                }
                if [[ "$(_jq '.name')" =~ ^"Release" ]]; then
                  echo "$(_jq '.tagName')" - "1.0.103"
                  if [[ ! "$(_jq '.tagName')" == "1.0.103" ]]; then
                    echo Deleting Release $(_jq '.name');
                    
                  fi
                fi
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
